config/routes.rb
Rails.application.routes.draw do
  
  resources :productorders do
    collection { post :update_paid}
  end
  resources :requests
  resources :fabrics
  devise_for :users
  resources :contacts
  
  resources :orders do
  	member { post :fulfill }
  end

  resources :clothes
  
  root to: "static_pages#home"
  match 'about', to: 'static_pages#about', via: 'get'
  match 'kenteclothes', to: 'fabrics#kenteclothes', via: 'get'
  match 'fabricsclothes', to: 'fabrics#fabricsclothes', via: 'get'
  match 'fascinators', to: 'fabrics#fascinators', via: 'get'
  match 'fabricsandclothes', to: 'static_pages#fabricsandclothes', via: 'get'
  match 'mydashboard', to: 'static_pages#mydashboard', via: 'get'
  match 'myorders', to: 'static_pages#myorders', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fabric.rb
class Fabric < ApplicationRecord
	mount_uploader :fabricimage, FabricimageUploader
	has_many :requests
	default_scope -> { order('created_at DESC') }
	before_create :generate_fabricordercode
	has_many :productorders

	def generate_fabricordercode
       self.price = "NFD" + rand(101..999).to_s + "-" + "NFD" + rand(10011..99099).to_s 
  end

end

app/controllers/fabrics_controller.rb
class FabricsController < ApplicationController
  before_action :set_fabric, only: [:show, :edit, :update, :destroy]

  # GET /fabrics
  # GET /fabrics.json
  def index
    @fabrics = Fabric.all
    @request = Request.new
  end

  # GET /fabrics/1
  # GET /fabrics/1.json
  def show
     @productorder = Productorder.new
  end

  # GET /fabrics/new 
  def new
    @fabric = Fabric.new
  end

  # GET /fabrics/1/edit
  def edit
  end

  def kenteclothes
    @kentefabs = Fabric.where(ctype: "kente").all
    @request = Request.new
  end

  def fabricsclothes
    @clothfabs = Fabric.where(ctype: "cloth").all
    @request = Request.new
  end

  def fascinators
    @fascinators = Fabric.where(ctype: "fascinator").all
    @request = Request.new
  end

  # POST /fabrics
  # POST /fabrics.json
  def create
    @fabric = Fabric.new(fabric_params)

    respond_to do |format|
      if @fabric.save
        format.html { redirect_to @fabric, notice: 'Fabric was successfully created.' }
        format.json { render :show, status: :created, location: @fabric }
      else
        format.html { render :new }
        format.json { render json: @fabric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fabrics/1
  # PATCH/PUT /fabrics/1.json
  def update
    respond_to do |format|
      if @fabric.update(fabric_params)
        format.html { redirect_to @fabric, notice: 'Fabric was successfully updated.' }
        format.json { render :show, status: :ok, location: @fabric }
      else
        format.html { render :edit }
        format.json { render json: @fabric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fabrics/1
  # DELETE /fabrics/1.json
  def destroy
    @fabric.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Fabric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fabric
      @fabric = Fabric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fabric_params
      params.require(:fabric).permit(:title, :description, :fabricimage, :price, :ctype, :fabprice, :maleprice)
    end
end

app/helpers/fabrics_helper.rb
module FabricsHelper
end

app/views/fabrics/_fabric.html.erb
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="prophold">
        <a href="/fabrics/<%= fabric.id %>">
          <img src="<%= fabric.fabricimage %>" class="img-fluid">
        </a>
        <p style="text-align: left;  margin-top: 10px; margin-bottom: 0;">
        	<span style="font-weight: 500; font-size: 18px;"><%= fabric.title %></span><br>
        	<span style="font-weight: 300; font-size: 12px;"><%= fabric.price %></span><br>
        </p>

        <% if fabric.ctype == "kente" %>
          <p>
            <span>Price</span><br>
            <% if fabric.fabprice %>
            <span>$ <%= (fabric.fabprice / 5.1).round(1) %></span> <span style="font-size: 12px;"> Female price</span>
            <% end %>
            <br>
            <% if fabric.maleprice %>
          <span>$ <%= (fabric.maleprice / 5.1).round(1) %> <span style="font-size: 12px;"> Male price</span></span>
            <% end %>
        </p>
        <% else %>
        <p>
          <% if fabric.fabprice %>
          <span>$ <%= (fabric.fabprice / 5.1).round(1) %> </span> <span style="font-size: 12px;">Price</span>
          <% end %>
          <span style="font-size: 12px;">
            <% if fabric.ctype == "cloth" %>
             / yard
            <% end %>
          </span>
        </p>
        <% end %>

        <!-- 
        <%= link_to 'Destroy', fabric, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Edit', edit_fabric_path(fabric) %> 
        -->
        <p style="text-align: right;  margin-top: 0px; display: none;">
        	<a class="btn btn-warning bookbtn" data-toggle="modal" href="#bookTourModal_<%= fabric.id %>">Request for this Fabric</a>
        </p>
      </div>
    </div>

    <div class="modal fade" id="bookTourModal_<%= fabric.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Provide your valid details.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(@request) do |f| %>
        <%= hidden_field_tag :fabric_id, fabric.id %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label style="font-weight: 500;">Email</label>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Your name." %>
  </div>

  <div class="form-group">
    <label style="font-weight: 500;">Email</label>
    <%= f.text_field :email, :class => "form-control", :placeholder => "Your email." %>
  </div>

  <div class="form-group">
    <label style="font-weight: 500;">Phone Number</label>
    <%= f.text_field :phonenumber, :class => "form-control", :placeholder => "Your phone number." %>
  </div>

<% if fabric.ctype == "kente" %>
  <div class="form-group">
    <label style="font-weight: 500;">For Male / Female</label>
    <br>
    <span>
    <input type="radio" name="request[gender]" id="request_gender" value="male"/>
    Male
    <input type="radio" name="request[gender]" id="request_gender" value="female"/>
    Female
    </span>
    <div id="ValidationError" name="ValidationError" style="color: red;">
    
    </div>
  </div>

  <% end %>

  <% if fabric.ctype == "cloth" %>

  <div class="form-group">
    <label style="font-weight: 500;">How many yards of cloth</label>
    <select class="form-control" name="request[yards]" id="request_yards">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
      <option value="5">5</option>
      <option value="6">6</option>
      <option value="7">7</option>
      <option value="8">8</option>
      <option value="9">9</option>
      <option value="10">10</option>
      <option value="11">11</option>
      <option value="12">12</option>
      <option value="13">13</option>
      <option value="14">14</option>
      <option value="15">15</option>
      <option value="16">16</option>
  </select>
  </div>

  <% end %>

  <p style="margin-top: 10px; font-weight: 500;"> Your prefered payment method.</p>
  <input type="radio" name="request[paymentmethod]" id="request_paymentmethod" name="order[delivery]"value="Mobile Money" onclick="calculateTotal()" />
  <label><span style="margin-right: 5px;">Mobie Money</span></label>

  <input type="radio" name="request[paymentmethod]" id="request_paymentmethod" value="cashapp" onclick="calculateTotal()" />
  <label><span style="margin-right: 5px;">pay with Cash App</span></label>
<br>

<p style="margin-top: 10px; font-weight: 500;">Your prefered delivery method.</p>
  <input type="radio" name="request[deliverydet]" id="request_deliverydet" value="Deliver to location" onclick="calculateTotal()" />
  <label><span style="margin-right: 5px;">Deliver to your location</span></label>

    <input type="radio" name="request[deliverydet]" id="request_deliverydet" value="Pick up from Shop" onclick="calculateTotal()" />
  <label><span style="margin-right: 5px;">DHL / Express delivery</span></label>
<br>

  
  <div class="field" style="display: none;">
    <%= f.label :fabric_id %>
    <%= f.number_field :fabric_id %>
  </div>

  
  
      </div>
      <div class="modal-footer">
        <input type="submit" value="Submit" onclick="return Validate();" />
      </div>
    <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
function Validate() {
    var radios = document.getElementsByName('request[gender]')

    for (var i = 0; i < radios.length; i++) {
        if (radios[i].checked) {
        // alert("Selected Value = " + radios[i].value);
        return true; // checked
    }
    };

    // not checked, show error
    document.getElementById('ValidationError').innerHTML = 'Please select a gender type!';
    return false;
}
</script>

app/views/fabrics/_form.html.erb
<%= form_for(fabric) do |f| %>
  <% if fabric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fabric.errors.count, "error") %> prohibited this fabric from being saved:</h2>

      <ul>
      <% fabric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :fabricimage %>
    <%= f.file_field :fabricimage, :class => "form-control" %>
  </div>


  <div class="form-group">
    <label>Female price</label>
    <%= f.number_field :fabprice, :class => "form-control" %>
  </div>

  <div class="form-group">
    <label>Male price</label>
    <%= f.number_field :maleprice, :class => "form-control" %>
  </div>

  

  <div class="form-group">
    <select class="form-control" name="fabric[ctype]" id="fabric_ctype" onchange="calculateTotal()" required>
      <option value="kente" name="fabric[ctype]" id="fabric_ctype">Kente Cloth</option>
      <option value="cloth" name="fabric[ctype]" id="fabric_ctype">Fabric Cloth</option>
      <option value="fascinator" name="fabric[ctype]" id="fabric_ctype">Fascinator</option>
  </select>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fabrics/edit.html.erb
<h1>Editing Fabric</h1>

<%= render 'form', fabric: @fabric %>

<%= link_to 'Show', @fabric %> |
<%= link_to 'Back', fabrics_path %>

app/views/fabrics/fabricsclothes.html.erb
<style type="text/css">
.aduins{
 background:linear-gradient(0deg,rgba(0,0,0,0.8),rgba(0,0,0,0.1)),url(https://nikasemo-static.s3-us-west-2.amazonaws.com/naaseonfabrics/5_yrfqo3.jpg);
  background-position:center;
  min-height: 200px;
}

.picshold{
  padding-top: 30px;
  padding-bottom: 50px;
}

.prophold{
  background-color: #ffffff;
  border-radius: 5px;
  padding: 20px;
  margin-bottom: 20px;
}

</style>
<body style="background-color: #f2f2f2;">
<section class="aduins">
  <div class="container">
    <div class="row" style="margin-top: 0px">
      <div class="col-lg-12">
        <h1 style="text-align: center; color: white; position: relative; top: 65px; font-weight: 900;  text-shadow: 1px 0px 6px rgba(0, 0, 0, 1);">Cloth Fabrics</h1>
      </div>
    </div>
  </div>
</section>
<br><br>
<section style="padding-right: 10px; padding-left: 10px;">
<h3 style="text-align: center;">Order cloth fabrics and have them delivered to your home!</h3>
<p style="text-align: center; font-weight: 300;">These fabrics are beautiful, scarce and hard to find. This promotion last for just a month! Request now before it gets late.</p>
</section>
<section class="picshold">
<div class="container">
  <div class="row">
   <%= render @clothfabs %>
</div>
</div>
</section>

<%= link_to "new fabric", new_fabric_path %>

</body>

app/views/fabrics/fascinators.html.erb
<style type="text/css">
.aduins{
 background:linear-gradient(0deg,rgba(0,0,0,0.8),rgba(0,0,0,0.1)),url(https://nikasemo-static.s3-us-west-2.amazonaws.com/fascinators.jpg);
  background-position:center;
  min-height: 200px;
}

.picshold{
  padding-top: 30px;
  padding-bottom: 50px;
}

.prophold{
  background-color: #ffffff;
  border-radius: 5px;
  padding: 20px;
  margin-bottom: 20px;
}

</style>
<body style="background-color: #f2f2f2;">
<section class="aduins">
  <div class="container">
    <div class="row" style="margin-top: 0px">
      <div class="col-lg-12">
        <h1 style="text-align: center; color: white; position: relative; top: 65px; font-weight: 900;  text-shadow: 1px 0px 6px rgba(0, 0, 0, 1);">Fascinators</h1>
      </div>
    </div>
  </div>
</section>
<br><br>
<section style="padding-right: 10px; padding-left: 10px;">
<h3 style="text-align: center;">Order fascinators and have them delivered to your home!</h3>
<p style="text-align: center; font-weight: 300;">These fascinators are beautiful, scarce and hard to find. This promotion last for just a month! Request now before it gets late.</p>
</section>
<section class="picshold">
<div class="container">
  <div class="row">
   <%= render @fascinators %>
</div>
</div>
</section>

<%= link_to "new fabric", new_fabric_path %>

</body>

app/views/fabrics/index.html.erb
<style type="text/css">
.aduins{
 background:linear-gradient(0deg,rgba(0,0,0,0.8),rgba(0,0,0,0.1)),url(https://res.cloudinary.com/nikasemo/image/upload/v1509993897/5_yrfqo3.jpg);
  background-position:center;
  min-height: 200px;
}

.picshold{
  padding-top: 30px;
  padding-bottom: 50px;
}

.prophold{
  background-color: #ffffff;
  border-radius: 5px;
  padding: 20px;
  margin-bottom: 20px;
}

</style>
<body style="background-color: #f2f2f2;">
<section class="aduins">
  <div class="container">
    <div class="row" style="margin-top: 70px">
      <div class="col-lg-12">
        <h1 style="text-align: center; color: white; position: relative; top: 65px; font-weight: 900;  text-shadow: 1px 0px 6px rgba(0, 0, 0, 1);">Fabrics Sale!!!</h1>
      </div>
    </div>
  </div>
</section>
<br><br>
<section style="padding-right: 10px; padding-left: 10px;">
<h3 style="text-align: center;">Order fabrics and have them delivered to your home!</h3>
<p style="text-align: center; font-weight: 300;">These fabrics are beautiful, scarce and hard to find. This promotion last for just a month! Request now before it gets late.</p>
</section>
<section class="picshold">
<div class="container">
  <div class="row">
   <%= render @fabrics %>
</div>
</div>
</section>

<%= link_to "new fabric", new_fabric_path %>

</body>

app/views/fabrics/kenteclothes.html.erb
<style type="text/css">
.aduins{
 background:linear-gradient(0deg,rgba(0,0,0,0.8),rgba(0,0,0,0.1)),url(https://nikasemo-static.s3-us-west-2.amazonaws.com/naaseonfabrics/colourful-ashanti-kente-cloth-from-ghana.jpg);
  background-position:center;
  min-height: 200px;
}

.picshold{
  padding-top: 30px;
  padding-bottom: 50px;
}

.prophold{
  background-color: #ffffff;
  border-radius: 5px;
  padding: 20px;
  margin-bottom: 20px;
}

</style>
<body style="background-color: #f2f2f2;">
<section class="aduins">
  <div class="container">
    <div class="row" style="margin-top: 0px">
      <div class="col-lg-12">
        <h1 style="text-align: center; color: white; position: relative; top: 65px; font-weight: 900;  text-shadow: 1px 0px 6px rgba(0, 0, 0, 1);">Authentic Hand Woven  Kente <br>
          <span style="font-weight: 400; font-size: 23px;">(Highest Quality Royalty Wear)</span>
        </h1>
      </div>
    </div>
  </div>
</section>
<br><br>
<section style="padding-right: 10px; padding-left: 10px;">
<h3 style="text-align: center;">Order Kente fabrics and have them delivered to your home!</h3>
<p style="text-align: center; font-weight: 300;">These fabrics are beautiful, scarce and hard to find. This promotion last for just a month! Request now before it gets late.</p>
</section>
<section class="picshold">
<div class="container">
  <div class="row">
   <%= render @kentefabs %>
</div>
</div>
</section>

<%= link_to "new fabric", new_fabric_path %>

</body>

app/views/fabrics/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<br><br><br><br>
			<h1>Add Fabric</h1>

			<%= render 'form', fabric: @fabric %>

			<%= link_to 'Back', fabrics_path %>

		</div>
	</div>
</div>

app/views/fabrics/show.html.erb
<style type="text/css">
	input[type="number"] {
  -webkit-appearance: textfield;
  -moz-appearance: textfield;
  appearance: textfield;
}

input[type=number]::-webkit-inner-spin-button,
input[type=number]::-webkit-outer-spin-button {
  -webkit-appearance: none;
}

.number-input {
  border: 2px solid #ddd;
  display: inline-flex;
}

.number-input,
.number-input * {
  box-sizing: border-box;
}

.number-input button {
  outline:none;
  -webkit-appearance: none;
  background-color: transparent;
  border: none;
  align-items: center;
  justify-content: center;
  width: 3rem;
  height: 3rem;
  cursor: pointer;
  margin: 0;
  position: relative;
}

.number-input button:before,
.number-input button:after {
  display: inline-block;
  position: absolute;
  content: '';
  width: 1rem;
  height: 2px;
  background-color: #212121;
  transform: translate(-50%, -50%);
}
.number-input button.plus:after {
  transform: translate(-50%, -50%) rotate(90deg);
}

.number-input input[type=number] {
  font-family: sans-serif;
  max-width: 5rem;
  padding: .5rem;
  border: solid #ddd;
  border-width: 0 2px;
  font-size: 2rem;
  height: 3rem;
  font-weight: bold;
  text-align: center;
}
</style>

<br><br>

<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<img src="<%= @fabric.fabricimage %>" class="img-fluid">
		</div>
		<div class="col-lg-5">
			<h4 style="margin-top: 30px;">Bonwire Kente (High Class)</h4>
			<p>
				<span>Brand: </span><span>Bonwire</span>
				<br>
				<span style="font-weight: 500; font-size: 13px;">Prorduct ID: <%= @fabric.price %></span>
			</p>
			<% if @fabric.ctype == "kente" %>
	          <p>
	            <span style="font-weight: 700;">Price</span><br>
	            <span style="font-size: 22px;">$ <%= (@fabric.fabprice / 5.1).round(1) %></span> <span style="font-size: 12px;"> Female price</span>
	            <br>
	            <span style="font-size: 16px;">GH&#162; <%= @fabric.fabprice %></span> <span style="font-size: 12px;"></span><br>
	          <span style="font-size: 22px;">$ <%= (@fabric.maleprice / 5.1).round(1) %> <span style="font-size: 12px;"> Male price</span></span>
	          <br>
	          <span style="font-size: 16px;">GH&#162; <%= @fabric.maleprice %></span> <span style="font-size: 12px;"></span><br>
	      	  </p>
	        <% else %>
	        <p>
	          <span style="font-size: 22px;">$ <%= (@fabric.fabprice / 5.1).round(1) %> </span> <span style="font-size: 12px;">Price</span>
	          <span style="font-size: 12px;">
	            <% if @fabric.ctype == "cloth" %>
	             / yard
	            <% end %>
	          </span>
	        </p>
	        <% end %>
	        <%= form_for(@productorder) do |f| %>
			  <% if @productorder.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@productorder.errors.count, "error") %> prohibited this productorder from being saved:</h2>

			      <ul>
			      <% @productorder.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			      </ul>
			    </div>
			  <% end %>

			  <div class="field" style="display: none;">
			    <%= f.label :fabric_id %>
			    <%= f.number_field :fabric_id, :value => "#{@fabric.id}" %>
			  </div>

			  <% if user_signed_in? %>
			  <div class="field" style="display: none;">
			    <%= f.label :user_id %>
			    <%= f.number_field :user_id, :value => "#{current_user.id}" %>
			  </div>
			  <% end %>
			  <div class="field">
			    <label style="font-weight: 700;">No. of Yards</label><br>
			    <div class="number-input">
				  <button type="button" onclick="this.parentNode.querySelector('input[type=number]').stepDown()" ></button>
				  <input class="quantity" min="0" name="productorder[yardsnumber]" id="productorder_yardsnumber" value="1" type="number">
				  <button type="button" onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="plus"></button>
				</div>
			  </div>
			  <div class="form-group" style="margin-top: 10px;">
			    <label style="font-weight: 700;">Yard</label><br>
			   	<input type="radio" value="halfpiece" name="productorder[yardtype]" id="productorder_yardtype" /> half piece 
			    <input type="radio" value="fullpiece" name="productorder[yardtype]" id="productorder_yardtype" /> full piece 
			  </div>
			  <div class="form-group">
			    <label style="font-weight: 700;">Do you want to sew with us?</label><br>
			   	<input type="radio" value="yes" name="productorder[sewornot]" id="productorder_sewornot" /> Yes 
			    <input type="radio" value="no" name="productorder[sewornot]" id="productorder_sewornot" /> No
			  </div>

			  <div class="form-group">
			    <label style="font-weight: 700;">What's your gender?</label><br>
			   	<input type="radio" value="male" name="productorder[gender]" id="productorder_gender" /> Male 
			    <input type="radio" value="female" name="productorder[gender]" id="productorder_gendert" /> Female
			  </div>

			<p>
				<% if user_signed_in? %>
					<button class="btn btn-lg btn-success" style="width: 100%;">
						<i class="fa fa-cart-plus" aria-hidden="true"></i> Place Order
					</button>
				<% else %>
					<button class="btn btn-lg btn-success" type="button" data-toggle="modal" href="#loginModal" style="width: 100%;">
						<i class="fa fa-cart-plus" aria-hidden="true"></i> Place Order
					</button>
				<% end %>
			</p>

			<% end %>
		</div>
	</div>
</div>
<br>
<br>

<script type="text/javascript">

	function incrementNumber(){

	}

	function decrementNumber(){

	}

</script>