config/routes.rb
Rails.application.routes.draw do
  
  resources :productorders do
    collection { post :update_paid}
  end
  resources :requests
  resources :fabrics
  devise_for :users
  resources :contacts
  
  resources :orders do
  	member { post :fulfill }
  end

  resources :clothes
  
  root to: "static_pages#home"
  match 'about', to: 'static_pages#about', via: 'get'
  match 'kenteclothes', to: 'fabrics#kenteclothes', via: 'get'
  match 'fabricsclothes', to: 'fabrics#fabricsclothes', via: 'get'
  match 'fascinators', to: 'fabrics#fascinators', via: 'get'
  match 'fabricsandclothes', to: 'static_pages#fabricsandclothes', via: 'get'
  match 'mydashboard', to: 'static_pages#mydashboard', via: 'get'
  match 'myorders', to: 'static_pages#myorders', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/productorder.rb
class Productorder < ApplicationRecord
	belongs_to :user, optional: :true
	belongs_to :fabric, optional: :true
end

app/controllers/productorders_controller.rb
class ProductordersController < ApplicationController
  before_action :set_productorder, only: [:show, :edit, :update, :destroy]

  # GET /productorders
  # GET /productorders.json
  def index
    @productorders = Productorder.all
  end

  # GET /productorders/1
  # GET /productorders/1.json
  def show
  end

  # GET /productorders/new
  def new
    @productorder = Productorder.new
  end

  # GET /productorders/1/edit
  def edit
  end

  # POST /productorders
  # POST /productorders.json
  def create
    @productorder = Productorder.new(productorder_params)

    respond_to do |format|
      if @productorder.save
        format.html { redirect_to :back, notice: 'Product order was successfully created.' }
        format.json { render :show, status: :created, location: @productorder }
      else
        format.html { render :new }
        format.json { render json: @productorder.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_paid
    productorderid = params[:productorder_id]
    @productorder = Productorder.find(productorderid)
    @productorder.update(paid: "true")
    render :status => 200,
           :json => @productorder
  end

  # PATCH/PUT /productorders/1
  # PATCH/PUT /productorders/1.json
  def update
    respond_to do |format|
      if @productorder.update(productorder_params)
        format.html { redirect_to @productorder, notice: 'Productorder was successfully updated.' }
        format.json { render :show, status: :ok, location: @productorder }
      else
        format.html { render :edit }
        format.json { render json: @productorder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productorders/1
  # DELETE /productorders/1.json
  def destroy
    @productorder.destroy
    respond_to do |format|
      format.html { redirect_to productorders_url, notice: 'Productorder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_productorder
      @productorder = Productorder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def productorder_params
      params.require(:productorder).permit(:fabric_id, :user_id, :yardsnumber, :yardtype, :sewornot, :paid, :gender)
    end
end

app/helpers/productorders_helper.rb
module ProductordersHelper
end

app/views/productorders/_form.html.erb
<%= form_for(productorder) do |f| %>
  <% if productorder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(productorder.errors.count, "error") %> prohibited this productorder from being saved:</h2>

      <ul>
      <% productorder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fabric_id %>
    <%= f.number_field :fabric_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :yardsnumber %>
    <%= f.number_field :yardsnumber %>
  </div>

  <div class="field">
    <%= f.label :yardtype %>
    <%= f.text_field :yardtype %>
  </div>

  <div class="field">
    <%= f.label :sewornot %>
    <%= f.text_field :sewornot %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productorders/edit.html.erb
<h1>Editing Productorder</h1>

<%= render 'form', productorder: @productorder %>

<%= link_to 'Show', @productorder %> |
<%= link_to 'Back', productorders_path %>

app/views/productorders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productorders</h1>

<table>
  <thead>
    <tr>
      <th>Fabric</th>
      <th>User</th>
      <th>Yardsnumber</th>
      <th>Yardtype</th>
      <th>Sewornot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productorders.each do |productorder| %>
      <tr>
        <td><%= productorder.fabric_id %></td>
        <td><%= productorder.user_id %></td>
        <td><%= productorder.yardsnumber %></td>
        <td><%= productorder.yardtype %></td>
        <td><%= productorder.sewornot %></td>
        <td><%= link_to 'Show', productorder %></td>
        <td><%= link_to 'Edit', edit_productorder_path(productorder) %></td>
        <td><%= link_to 'Destroy', productorder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Productorder', new_productorder_path %>

app/views/productorders/new.html.erb
<h1>New Productorder</h1>

<%= render 'form', productorder: @productorder %>

<%= link_to 'Back', productorders_path %>

app/views/productorders/show.html.erb
<br><br>
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <div class="row">
      <div class="col-lg-3 col-3">
      <img src="<%= @productorder.fabric.fabricimage %>" class="img-fluid">
    </div>
    <div class="col-lg-9 col-9">
      <p style="margin-bottom: 0px;"><%= @productorder.fabric.price %></p>
      <% if @productorder.fabric.ctype == "kente" %>
            <p style="margin-bottom: 5px;">
              <span style="font-weight: 700;">Price</span><br>
              <span style="font-size: 22px;">$ <%= (@productorder.fabric.fabprice / 5.1).round(1) %></span> <span style="font-size: 12px;"> Female price</span>
              <br>
              <span style="font-size: 16px;">GH&#162; <%= @productorder.fabric.fabprice %></span> <span style="font-size: 12px;"></span><br>
            <span style="font-size: 22px;">$ <%= (@productorder.fabric.maleprice / 5.1).round(1) %> <span style="font-size: 12px;"> Male price</span></span>
            <br>
            <span style="font-size: 16px;">GH&#162; <%= @productorder.fabric.maleprice %></span> <span style="font-size: 12px;"></span><br>
            </p>
          <% else %>
          <p>
            <span style="font-size: 22px;">$ <%= (@productorder.fabric.fabprice / 5.1).round(1) %> </span> <span style="font-size: 12px;">Price</span>
            <span style="font-size: 12px;">
              <% if @productorder.fabric.ctype == "cloth" %>
               / yard
              <% end %>
            </span>
          </p>
          <% end %>
          <p style="margin-bottom: 5px;">Paid: <%= @productorder.paid %></p>
          <% if @productorder.paid == false %>
            <p>
          <form >
          <script src="https://js.paystack.co/v1/inline.js"></script>
          <p style="text-align: left;">
          <button type="button" class="btn btn-lg btn-success btnformpay" id="paymentbutton" onclick="payWithPaystack()"> 
          Make Payment 
          </button>
        </form>
          </p>
          <% else %>
            <p>Awaiting fulfilment</p>
          <% end %>
    </div>
  </div>

  </div>
  </div>
</div>
<br><br><br>


      
   


<script>

 var price = 0;

  <% if @productorder.gender == "male" %>
    price = <%= @productorder.fabric.maleprice %>
  <% end %>

  <% if @productorder.gender == "female" %>
    price = <%= @productorder.fabric.fabprice %>
  <% end %>

  

  function payWithPaystack(){
     
    var handler = PaystackPop.setup({
      key: 'pk_live_8a40483553b17e3ddefa0cd1a64e62c88677433a',
      email: "<%= current_user.email.to_s %>",
      amount: price * 100,
      currency: "GHS",
      ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
      metadata: {
         custom_fields: [
            {
                display_name: "Mobile Number",
                variable_name: "mobile_number",
                value: "+233553393260"
            }
         ]
      },
      callback: function(response){
          
       $.ajax('update_paid', {
        type: 'POST',
        data: {
          productorder_id: <%= @productorder.id.to_i %>
        },
        error: function(jqXHR, textStatus, errorThrown) {
          return console.log("AJAX Error: " + errorThrown);
        },
        success: function(data, textStatus, jqXHR) {
          
          console.log(data);
          location.reload;
          return console.log("Payment status ypdated");
        }
      });

          
      },
      onClose: function(){
          alert('window closed');
      }
    });
    handler.openIframe();
  }
</script>