config/routes.rb
Rails.application.routes.draw do
  
  resources :productorders do
    collection { post :update_paid}
  end
  resources :requests
  resources :fabrics
  devise_for :users
  resources :contacts
  
  resources :orders do
  	member { post :fulfill }
  end

  resources :clothes
  
  root to: "static_pages#home"
  match 'about', to: 'static_pages#about', via: 'get'
  match 'kenteclothes', to: 'fabrics#kenteclothes', via: 'get'
  match 'fabricsclothes', to: 'fabrics#fabricsclothes', via: 'get'
  match 'fascinators', to: 'fabrics#fascinators', via: 'get'
  match 'fabricsandclothes', to: 'static_pages#fabricsandclothes', via: 'get'
  match 'mydashboard', to: 'static_pages#mydashboard', via: 'get'
  match 'myorders', to: 'static_pages#myorders', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/clothe.rb
class Clothe < ApplicationRecord
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  before_action :set_clothe, only: [:show, :edit, :update, :destroy]

  # GET /clothes
  # GET /clothes.json
  def index
    @clothes = Clothe.all
  end

  # GET /clothes/1
  # GET /clothes/1.json
  def show
  end

  # GET /clothes/new
  def new
    @clothe = Clothe.new
  end

  # GET /clothes/1/edit
  def edit
  end

  # POST /clothes
  # POST /clothes.json
  def create
    @clothe = Clothe.new(clothe_params)

    respond_to do |format|
      if @clothe.save
        format.html { redirect_to @clothe, notice: 'Clothe was successfully created.' }
        format.json { render :show, status: :created, location: @clothe }
      else
        format.html { render :new }
        format.json { render json: @clothe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clothes/1
  # PATCH/PUT /clothes/1.json
  def update
    respond_to do |format|
      if @clothe.update(clothe_params)
        format.html { redirect_to @clothe, notice: 'Clothe was successfully updated.' }
        format.json { render :show, status: :ok, location: @clothe }
      else
        format.html { render :edit }
        format.json { render json: @clothe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clothes/1
  # DELETE /clothes/1.json
  def destroy
    @clothe.destroy
    respond_to do |format|
      format.html { redirect_to clothes_url, notice: 'Clothe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clothe
      @clothe = Clothe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clothe_params
      params.require(:clothe).permit(:name, :description, :category)
    end
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/views/clothes/_form.html.erb
<%= form_for(clothe) do |f| %>
  <% if clothe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clothe.errors.count, "error") %> prohibited this clothe from being saved:</h2>

      <ul>
      <% clothe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clothes/edit.html.erb
<h1>Editing Clothe</h1>

<%= render 'form', clothe: @clothe %>

<%= link_to 'Show', @clothe %> |
<%= link_to 'Back', clothes_path %>

app/views/clothes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clothes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clothes.each do |clothe| %>
      <tr>
        <td><%= clothe.name %></td>
        <td><%= clothe.description %></td>
        <td><%= clothe.category %></td>
        <td><%= link_to 'Show', clothe %></td>
        <td><%= link_to 'Edit', edit_clothe_path(clothe) %></td>
        <td><%= link_to 'Destroy', clothe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clothe', new_clothe_path %>

app/views/clothes/new.html.erb
<h1>New Clothe</h1>

<%= render 'form', clothe: @clothe %>

<%= link_to 'Back', clothes_path %>

app/views/clothes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @clothe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @clothe.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @clothe.category %>
</p>

<%= link_to 'Edit', edit_clothe_path(@clothe) %> |
<%= link_to 'Back', clothes_path %>