config/routes.rb
Rails.application.routes.draw do
  
  resources :productorders do
    collection { post :update_paid}
  end
  resources :requests
  resources :fabrics
  devise_for :users
  resources :contacts
  
  resources :orders do
  	member { post :fulfill }
  end

  resources :clothes
  
  root to: "static_pages#home"
  match 'about', to: 'static_pages#about', via: 'get'
  match 'kenteclothes', to: 'fabrics#kenteclothes', via: 'get'
  match 'fabricsclothes', to: 'fabrics#fabricsclothes', via: 'get'
  match 'fascinators', to: 'fabrics#fascinators', via: 'get'
  match 'fabricsandclothes', to: 'static_pages#fabricsandclothes', via: 'get'
  match 'mydashboard', to: 'static_pages#mydashboard', via: 'get'
  match 'myorders', to: 'static_pages#myorders', via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :fabric
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_filter :load_fabric, only: [:new, :create]
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.fabric = @fabric
    respond_to do |format|
      if @request.save
        format.html { redirect_to @request }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    def load_fabric
      @fabric = Fabric.find_by(id: params[:fabric_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:name, :email, :phonenumber, :paymentmethod, :deliverydet, :fabric_id, :gender, :yards)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phonenumber %>
    <%= f.text_field :phonenumber %>
  </div>

  <div class="field">
    <%= f.label :paymentmethod %>
    <%= f.text_field :paymentmethod %>
  </div>

  <div class="field">
    <%= f.label :deliverydet %>
    <%= f.text_field :deliverydet %>
  </div>

  <div class="field">
    <%= f.label :fabric_id %>
    <%= f.number_field :fabric_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phonenumber</th>
      <th>Paymentmethod</th>
      <th>Deliverydet</th>
      <th>Fabric</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= request.email %></td>
        <td><%= request.phonenumber %></td>
        <td><%= request.paymentmethod %></td>
        <td><%= request.deliverydet %></td>
        <td><%= request.fabric_id %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<br><br><br><br><br>
<div class="container" style="font-family: 'Poppins', sans-serif;">
  <div class="row">
    <div class="col-lg-12">
      <h3 style="text-align: center;">Your Order details</h3>
      <br>
    </div>
    <div class="col-lg-5">
      <img src="<%= @request.fabric.fabricimage %>" class="img-fluid">
    </div>
    <div class="col-lg-7">
      <p>
        <strong>Name:</strong>
        <%= @request.name %>
      </p>


      <p>
        <strong>Email:</strong>
        <%= @request.email %>
      </p>

      <p>
        <strong>Phonenumber:</strong>
        <%= @request.phonenumber %>
      </p>

      <p>
        <strong>Paymentmethod:</strong>
        <%= @request.paymentmethod %>
      </p>

      <p>
        <strong>Deliverydet:</strong>
        <%= @request.deliverydet %>
      </p>

     
        <% if @request.paymentmethod == "cashapp" %>
         <p>
          <span>Make payment of </span>
          <% if @request.gender == "male" %>
            $<%= (@request.fabric.maleprice / 5.9).round(1) %>
          <% end %>
          <% if @request.gender == "female" %>
            $<%= (@request.fabric.fabprice / 5.9).round(1) %>
          <% end %>
           <span> to CashApp account with name id <strong>CarolineBrew</strong></span>
         </p>
        <% else %>
      

      <form >
      <script src="https://js.paystack.co/v1/inline.js"></script>
      <p style="text-align: left;">
      <button type="button" class="btn btn-lg btn-success btnformpay" id="paymentbutton" onclick="payWithPaystack()"> 
      Make Payment 
      </button>
      </p>
      
      <!--
      <a id="paymentconfirm" style="display: none;" href="/api/v1/updateuserpaid?user_id=1sLRbhzJ3oOp6Togw7AfCMPjhLf2&subscripttype=semester">Confirm Payment</a>
      -->
      <span id="myuserid" style="color: black; font-size: 30px;"> </span>
    </form>
    <% end %>
    </div>
  </div>
</div>
<br><br><br>





<script>

 var price = 0;

  <% if @request.gender == "male" %>
    price = <%= @request.fabric.maleprice %>
  <% end %>

  <% if @request.gender == "female" %>
    price = <%= @request.fabric.fabprice %>
  <% end %>

  function payWithPaystack(){
     
    var handler = PaystackPop.setup({
      key: 'pk_live_8a40483553b17e3ddefa0cd1a64e62c88677433a',
      email: "<%= @request.email.to_s %>",
      amount: price * 100,
      currency: "GHS",
      ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
      metadata: {
         custom_fields: [
            {
                display_name: "Mobile Number",
                variable_name: "mobile_number",
                value: "+233553393260"
            }
         ]
      },
      callback: function(response){
          const queryString = window.location.search;
          const urlParams = new URLSearchParams(queryString);
          const user_id = urlParams.get('user_id')
            console.log(queryString);
        //   alert('success. transaction ref is ' + response.reference + ' ' + user_id);
          // window.open("https://www.w3schools.com");
          document.getElementById('paymentbutton').style.display = 'none';
          document.getElementById('paymentconfirm').style.display = 'block';

          document.getElementById('mptext').style.display = 'none';
          document.getElementById('pconfmtext').style.display = 'block';

          
      },
      onClose: function(){
          alert('window closed');
      }
    });
    handler.openIframe();
  }
</script>